### ISSUE TITLE
sudo apt-get update

### ISSUE THREAD

**Issue by basha2006** [almul8ab/yamosa#1]
sudo apt-get install python3.10

sudo apt install postgresql postgresql-contrib
sudo su - postgres bash -c "psql -c \"ALTER USER postgres WITH PASSWORD 'your_password';\" && createdb aljoker -O postgres"
postgresql://postgres:your_password@localhost:5432/aljoker
sudo apt update && sudo apt upgrade -y

sudo apt install --no-install-recommends -y curl git libffi-dev libjpeg-dev libwebp-dev python3-lxml python3-psycopg2 libpq-dev libcurl4-openssl-dev libxml2-dev libxslt1-dev python3-pip python3-sqlalchemy openssl wget python3 python3-dev libreadline-dev libyaml-dev gcc zlib1g ffmpeg libssl-dev libgconf-2-4 libxi6 unzip libopus0 libopus-dev python3-venv libmagickwand-dev pv tree medi
pip3 install Telethon

**Comment by basha2006** [comment]
ت

**Comment by redaiq90** [comment]
???
